"""Changed field hard_constraints and added job_titles to UserFeatures

Revision ID: 057965abc440
Revises: 124369ec0b60
Create Date: 2026-09-29 14:16:43.188952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '057965abc440'
down_revision: Union[str, Sequence[str], None] = '124369ec0b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'user_features',
        sa.Column(
            'job_titles',
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )

    op.alter_column(
        'user_features',
        'job_titles',
        server_default=None,
    )

    op.alter_column(
        'user_features',
        'hard_constraints',
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using='to_jsonb(hard_constraints)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_features',
        'hard_constraints',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
        postgresql_using=(
            "ARRAY("
            "SELECT jsonb_array_elements_text(hard_constraints)"
            ")"
        ),
    )

    op.drop_column(
        'user_features',
        'job_titles',
    )
    # ### end Alembic commands ###
