"""Added salary field to UserProfile

Revision ID: 124369ec0b60
Revises: 68f9e700df0f
Create Date: 2026-09-29 13:48:07.015306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124369ec0b60'
down_revision: Union[str, Sequence[str], None] = '68f9e700df0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'salary')
    # ### end Alembic commands ###
