"""created user profile

Revision ID: 1a4ef4197138
Revises: f84d8432dc3b
Create Date: 2026-09-01 14:51:59.447368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4ef4197138'
down_revision: Union[str, Sequence[str], None] = 'f84d8432dc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('preferred_work_days_per_week', sa.Integer(), nullable=True),
    sa.Column('preferred_work_hours_per_day', sa.Float(), nullable=True),
    sa.Column('flexible_schedule_needed', sa.Boolean(), nullable=True),
    sa.Column('overtime_tolerance', sa.String(), nullable=True),
    sa.Column('preferred_end_time', sa.Time(), nullable=True),
    sa.Column('weekend_work', sa.String(), nullable=True),
    sa.Column('night_work_tolerance', sa.String(), nullable=True),
    sa.Column('shift_work_tolerance', sa.String(), nullable=True),
    sa.Column('business_trip_tolerance', sa.String(), nullable=True),
    sa.Column('client_communication_tolerance', sa.String(), nullable=True),
    sa.Column('team_communication_tolerance', sa.String(), nullable=True),
    sa.Column('meeting_tolerance', sa.String(), nullable=True),
    sa.Column('public_speaking_tolerance', sa.String(), nullable=True),
    sa.Column('phone_call_tolerance', sa.String(), nullable=True),
    sa.Column('customer_support_tolerance', sa.String(), nullable=True),
    sa.Column('conflict_tolerance', sa.String(), nullable=True),
    sa.Column('multitasking_tolerance', sa.String(), nullable=True),
    sa.Column('deadline_tolerance', sa.String(), nullable=True),
    sa.Column('context_switching_tolerance', sa.String(), nullable=True),
    sa.Column('ambiguity_tolerance', sa.String(), nullable=True),
    sa.Column('information_overload_tolerance', sa.String(), nullable=True),
    sa.Column('interruptions_tolerance', sa.String(), nullable=True),
    sa.Column('burnout_sensitivity', sa.String(), nullable=True),
    sa.Column('social_overload_sensitivity', sa.String(), nullable=True),
    sa.Column('preferred_team_size', sa.String(), nullable=True),
    sa.Column('preferred_management_style', sa.String(), nullable=True),
    sa.Column('preferred_task_structure', sa.String(), nullable=True),
    sa.Column('task_variety_preference', sa.String(), nullable=True),
    sa.Column('autonomy_level', sa.String(), nullable=True),
    sa.Column('feedback_frequency_preference', sa.String(), nullable=True),
    sa.Column('noise_tolerance', sa.String(), nullable=True),
    sa.Column('open_space_tolerance', sa.String(), nullable=True),
    sa.Column('preferred_work_formats', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('physical_activity_tolerance', sa.String(), nullable=True),
    sa.Column('standing_work_tolerance', sa.String(), nullable=True),
    sa.Column('travel_tolerance', sa.String(), nullable=True),
    sa.Column('motivation_factors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('income_importance', sa.Integer(), nullable=True),
    sa.Column('stability_importance', sa.Integer(), nullable=True),
    sa.Column('interesting_tasks_importance', sa.Integer(), nullable=True),
    sa.Column('professional_growth_importance', sa.Integer(), nullable=True),
    sa.Column('horizontal_growth_importance', sa.Integer(), nullable=True),
    sa.Column('vertical_growth_importance', sa.Integer(), nullable=True),
    sa.Column('autonomy_level_importance', sa.Integer(), nullable=True),
    sa.Column('flexible_schedule_needed_importance', sa.Integer(), nullable=True),
    sa.Column('work_life_balance_importance', sa.Integer(), nullable=True),
    sa.Column('remote_work_importance', sa.Integer(), nullable=True),
    sa.Column('social_environment_importance', sa.Integer(), nullable=True),
    sa.Column('recognition_importance', sa.Integer(), nullable=True),
    sa.Column('meaningful_work_importance', sa.Integer(), nullable=True),
    sa.Column('variety_importance', sa.Integer(), nullable=True),
    sa.Column('creativity_importance', sa.Integer(), nullable=True),
    sa.Column('dms_importance', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
