"""upgrade resume document

Revision ID: 4fd79a6a3263
Revises: 89fcdad8eb1b
Create Date: 2026-09-08 17:00:36.122455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd79a6a3263'
down_revision: Union[str, Sequence[str], None] = '89fcdad8eb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_documents', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('resume_documents', 'file_path')
    op.drop_column('resume_documents', 'mime_type')
    op.drop_column('resume_documents', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_documents', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resume_documents', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resume_documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('resume_documents', 'text')
    # ### end Alembic commands ###
