"""Changed column experience_resume

Revision ID: 68f9e700df0f
Revises: 5fc194448d8e
Create Date: 2026-09-25 16:59:30.519725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68f9e700df0f'
down_revision: Union[str, Sequence[str], None] = '5fc194448d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'resume_features',
        'experience_resume',
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using='to_jsonb(experience_resume)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'resume_features',
        'experience_resume',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
        postgresql_using=(
            'ARRAY('
            'SELECT value::text '
            'FROM jsonb_array_elements(experience_resume) AS value'
            ')'
        ),
    )
    # ### end Alembic commands ###
