"""add refresh tokens

Revision ID: 808e533a898c
Revises: 4fd79a6a3263
Create Date: 2026-09-16 17:38:15.052665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808e533a898c'
down_revision: Union[str, Sequence[str], None] = '4fd79a6a3263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_features',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_titles', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('hard_skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('soft_skills', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('experience', sa.Float(), nullable=True),
    sa.Column('projects', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('weaknesses', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('strengths', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('experience_resume', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_features')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
