"""add resume document

Revision ID: 89fcdad8eb1b
Revises: 1a4ef4197138
Create Date: 2026-09-08 16:46:35.763295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fcdad8eb1b'
down_revision: Union[str, Sequence[str], None] = '1a4ef4197138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_features',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hard_constraints', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('preferences', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tolerances', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('context', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_features')
    op.drop_table('resume_documents')
    # ### end Alembic commands ###
